// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFUchBVSJhJTyIpB796gtxn2uvoqwtAr8',
    appId: '1:724176613929:web:f415f42c85b1ad48eb6238',
    messagingSenderId: '724176613929',
    projectId: 'mad-lab-89d6c',
    authDomain: 'mad-lab-89d6c.firebaseapp.com',
    storageBucket: 'mad-lab-89d6c.firebasestorage.app',
    measurementId: 'G-CGC4B0S2NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPyqp40gVL7snItfGtH9um-l8-RQiiFic',
    appId: '1:724176613929:android:84c60438873fe553eb6238',
    messagingSenderId: '724176613929',
    projectId: 'mad-lab-89d6c',
    storageBucket: 'mad-lab-89d6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEuevHLbuIjbpsAj8cd7Kp1-OThpjy0PU',
    appId: '1:724176613929:ios:e1678554e34d0089eb6238',
    messagingSenderId: '724176613929',
    projectId: 'mad-lab-89d6c',
    storageBucket: 'mad-lab-89d6c.firebasestorage.app',
    iosClientId: '724176613929-21rbn9upfrbjpuuicjce039g5pm9h7qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEuevHLbuIjbpsAj8cd7Kp1-OThpjy0PU',
    appId: '1:724176613929:ios:e1678554e34d0089eb6238',
    messagingSenderId: '724176613929',
    projectId: 'mad-lab-89d6c',
    storageBucket: 'mad-lab-89d6c.firebasestorage.app',
    iosClientId: '724176613929-21rbn9upfrbjpuuicjce039g5pm9h7qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFUchBVSJhJTyIpB796gtxn2uvoqwtAr8',
    appId: '1:724176613929:web:7c91171465fe5f46eb6238',
    messagingSenderId: '724176613929',
    projectId: 'mad-lab-89d6c',
    authDomain: 'mad-lab-89d6c.firebaseapp.com',
    storageBucket: 'mad-lab-89d6c.firebasestorage.app',
    measurementId: 'G-K329M7WH3R',
  );
}
